# Generated by Django 5.0.6 on 2024-06-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(default='Рассылка', max_length=255, verbose_name='Имя рассылки'),
        ),
    ]
