# Generated by Django 5.0.6 on 2024-06-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя рассылки'),
        ),
    ]
