# Generated by Django 5.0.6 on 2024-06-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_client_owner_mailing_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_disable_mailing', 'Can disable mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
